In [1]:
import random
import numpy as np
from cs231n.data_utils import load_CIFAR10
import matplotlib.pyplot as plt

# This is a bit of magic to make matplotlib figures appear inline in the
# notebook rather than in a new window.
%matplotlib inline
plt.rcParams['figure.figsize'] = (10.0, 8.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

# Some more magic so that the notebook will reload external python modules;
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2
# Load the raw CIFAR-10 data.
cifar10_dir = 'cs231n/datasets/cifar-10-batches-py'
X_train, y_train, X_test, y_test = load_CIFAR10(cifar10_dir)

# As a sanity check, we print out the size of the training and test data.
print 'Training data shape: ', X_train.shape
print 'Training labels shape: ', y_train.shape
print 'Test data shape: ', X_test.shape
print 'Test labels shape: ', y_test.shape
num_training = 49000
num_validation = 1000
num_test = 1000
num_dev = 500

# Our validation set will be num_validation points from the original
# training set.
mask = range(num_training, num_training + num_validation)
X_val = X_train[mask]
y_val = y_train[mask]

# Our training set will be the first num_train points from the original
# training set.
mask = range(num_training)
X_train = X_train[mask]
y_train = y_train[mask]

# We will also make a development set, which is a small subset of
# the training set.
mask = np.random.choice(num_training, num_dev, replace=False)
X_dev = X_train[mask]
y_dev = y_train[mask]

# We use the first num_test points of the original test set as our
# test set.
mask = range(num_test)
X_test = X_test[mask]
y_test = y_test[mask]

print 'Train data shape: ', X_train.shape
print 'Train labels shape: ', y_train.shape
print 'Validation data shape: ', X_val.shape
print 'Validation labels shape: ', y_val.shape
print 'Test data shape: ', X_test.shape
print 'Test labels shape: ', y_test.shape

# Preprocessing: reshape the image data into rows
X_train = np.reshape(X_train, (X_train.shape[0], -1))
X_val = np.reshape(X_val, (X_val.shape[0], -1))
X_test = np.reshape(X_test, (X_test.shape[0], -1))
X_dev = np.reshape(X_dev, (X_dev.shape[0], -1))

# As a sanity check, print out the shapes of the data
print 'Training data shape: ', X_train.shape
print 'Validation data shape: ', X_val.shape
print 'Test data shape: ', X_test.shape
print 'dev data shape: ', X_dev.shape
# second: subtract the mean image from train and test data
X_train -= mean_image
X_val -= mean_image
X_test -= mean_image
X_dev -= mean_image

# third: append the bias dimension of ones (i.e. bias trick) so that our SVM
# only has to worry about optimizing a single weight matrix W.
X_train = np.hstack([X_train, np.ones((X_train.shape[0], 1))])
X_val = np.hstack([X_val, np.ones((X_val.shape[0], 1))])
X_test = np.hstack([X_test, np.ones((X_test.shape[0], 1))])
X_dev = np.hstack([X_dev, np.ones((X_dev.shape[0], 1))])

print X_train.shape, X_val.shape, X_test.shape, X_dev.shape

Training data shape:  (50000, 32, 32, 3)
Training labels shape:  (50000,)
Test data shape:  (10000, 32, 32, 3)
Test labels shape:  (10000,)
Train data shape:  (49000, 32, 32, 3)
Train labels shape:  (49000,)
Validation data shape:  (1000, 32, 32, 3)
Validation labels shape:  (1000,)
Test data shape:  (1000, 32, 32, 3)
Test labels shape:  (1000,)
Training data shape:  (49000, 3072)
Validation data shape:  (1000, 3072)
Test data shape:  (1000, 3072)
dev data shape:  (500, 3072)


NameError: name 'mean_image' is not defined

In [2]:
mean_image = np.mean(X_train, axis=0)
X_train -= mean_image
X_val -= mean_image
X_test -= mean_image
X_dev -= mean_image

# third: append the bias dimension of ones (i.e. bias trick) so that our SVM
# only has to worry about optimizing a single weight matrix W.
X_train = np.hstack([X_train, np.ones((X_train.shape[0], 1))])
X_val = np.hstack([X_val, np.ones((X_val.shape[0], 1))])
X_test = np.hstack([X_test, np.ones((X_test.shape[0], 1))])
X_dev = np.hstack([X_dev, np.ones((X_dev.shape[0], 1))])

print X_train.shape, X_val.shape, X_test.shape, X_dev.shape

(49000, 3073) (1000, 3073) (1000, 3073) (500, 3073)


In [3]:
W = np.random.randn(3073, 10) * 0.0001
print W.shape

(3073, 10)


In [5]:
dW = np.zeros(W.shape)
num_classes = W.shape[1]
num_train = X_train.shape[0]
loss = 0.0

In [6]:
print num_train

49000


In [7]:
X=X_train

In [9]:
y=y_train
i=1
scores = X[i].dot(W)
correct_class_score = scores[y[i]]

In [11]:
scores.shape

(10,)

In [12]:
for j in xrange(num_classes):
      if j == y[i]:
        continue
      margin = scores[j] - correct_class_score + 1 # note delta = 1
      if margin > 0:
        loss += margin
        dW[y[i],:] -= X[:,i].T
        dW[j,:] += X[:,i].T

ValueError: operands could not be broadcast together with shapes (10,) (49000,) (10,) 

In [15]:
dW[y[i],:].shape,dW.shape

((10,), (3073, 10))

In [25]:
dW[:,y[i]].shape 

(3073,)

In [28]:
X.shape[1]

3073

In [27]:
W.shape[0]

3073

In [ ]:
num_classes = W.shape[0]
num_train = X.shape[1]
loss = 0.0
for i in xrange(num_train):
scores = W.dot(X[:, i])
correct_class_score = scores[y[i]]
for j in xrange(num_classes):
  if j == y[i]:
    continue
  margin = scores[j] - correct_class_score + 1 # note delta = 1
  if margin > 0:
    loss += margin

    # Compute gradients (one inner and one outer sum)
    # Wonderfully compact and hard to read
    dW[:,y[i]] -= X[:,i].T # this is really a sum over j != y_i
    dW[:,j] += X[:,i].T # sums each contribution of the x_i's

# Right now the loss is a sum over all training examples, but we want it
# to be an average instead so we divide by num_train.
loss /= num_train

# Same with gradient
dW /= num_train

# Add regularization
loss += 0.5 * reg * np.sum(W * W)

# Gradient regularization that carries through per https://piazza.com/class/i37qi08h43qfv?cid=118
dW += reg*W

In [1]:
import numpy as np

In [7]:
np.arange?

In [9]:
x=np.random.rand

TypeError: an integer is required

In [7]:
import numpy as np

In [3]:
np.log?

In [4]:
2-True

1

In [5]:
2-False

2

In [32]:
x= np.random.random([5,5])

In [9]:
x

array([[ 0.2720187 ,  0.97632393,  0.71779448,  0.92462464,  0.4505595 ],
       [ 0.61581216,  0.52246721,  0.73815943,  0.71889399,  0.57102191],
       [ 0.93412078,  0.25375668,  0.08164052,  0.25957994,  0.11910078]])

In [10]:
y=np.sum(x,axis=1)

In [11]:
y

array([ 3.34132127,  3.1663547 ,  1.64819871])

In [12]:
y[0]-=4

In [13]:
y

array([-0.65867873,  3.1663547 ,  1.64819871])

In [16]:
np.maximum(y,0)

array([ 0.        ,  3.1663547 ,  1.64819871])

In [19]:
y=np.arange(5)

In [38]:
y

array([0, 1, 4, 3, 4])

In [24]:
x[y,np.arange(5)]=1

TypeError: only length-1 arrays can be converted to Python scalars

In [40]:
m=np.zeros(x.shape)
m[np.arange(5),y]=1
x*m

array([[ 0.20127429,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.18447166,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.99668441],
       [ 0.        ,  0.        ,  0.        ,  0.90906978,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.86406241]])

In [41]:
x

array([[ 0.20127429,  0.08579939,  0.96168566,  0.61615875,  0.4610435 ],
       [ 0.80243097,  0.18447166,  0.75530769,  0.86546723,  0.22394686],
       [ 0.72515486,  0.84328515,  0.96656337,  0.83344163,  0.99668441],
       [ 0.31417611,  0.70100598,  0.48994293,  0.90906978,  0.06745098],
       [ 0.33514456,  0.76922868,  0.95015824,  0.91250912,  0.86406241]])

In [42]:
np.sum(x[:3,:],axis=0)

array([ 1.72886012,  1.11355619,  2.68355672,  2.31506761,  1.68167477])

In [44]:
y=np.ones((3,4))

In [45]:
y

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [49]:
np.sum(y,axis=0).reshape(1,-1)

array([[ 3.,  3.,  3.,  3.]])

In [50]:
x[:3,:].reshape(-1,1)

array([[ 0.20127429],
       [ 0.08579939],
       [ 0.96168566],
       [ 0.61615875],
       [ 0.4610435 ],
       [ 0.80243097],
       [ 0.18447166],
       [ 0.75530769],
       [ 0.86546723],
       [ 0.22394686],
       [ 0.72515486],
       [ 0.84328515],
       [ 0.96656337],
       [ 0.83344163],
       [ 0.99668441]])